services:
  app:
    build:
      args:
        APP_NAME: ${APP_NAME}
        BROADCAST_CONNECTION: ${BROADCAST_CONNECTION}
        PUSHER_APP_KEY: ${PUSHER_APP_KEY}
        PUSHER_APP_CLUSTER: ${PUSHER_APP_CLUSTER}
        VITE_FIREBASE_API_KEY: ${VITE_FIREBASE_API_KEY}
        VITE_FIREBASE_AUTH_DOMAIN: ${VITE_FIREBASE_AUTH_DOMAIN}
        VITE_FIREBASE_PROJECT_ID: ${VITE_FIREBASE_PROJECT_ID}
        VITE_FIREBASE_STORAGE_BUCKET: ${VITE_FIREBASE_STORAGE_BUCKET}
      context: .
      dockerfile: Dockerfile
      target: app
    container_name: app
    env_file:
      - .env
    environment:
      APP_SEED: "true"
    command: start-fpm
    depends_on:
      mysql:
        condition: service_healthy

  queue:
    build:
      args:
          APP_NAME: ${APP_NAME}
          BROADCAST_CONNECTION: ${BROADCAST_CONNECTION}
          PUSHER_APP_KEY: ${PUSHER_APP_KEY}
          PUSHER_APP_CLUSTER: ${PUSHER_APP_CLUSTER}
          VITE_FIREBASE_API_KEY: ${VITE_FIREBASE_API_KEY}
          VITE_FIREBASE_AUTH_DOMAIN: ${VITE_FIREBASE_AUTH_DOMAIN}
          VITE_FIREBASE_PROJECT_ID: ${VITE_FIREBASE_PROJECT_ID}
          VITE_FIREBASE_STORAGE_BUCKET: ${VITE_FIREBASE_STORAGE_BUCKET}
      context: .
      dockerfile: Dockerfile
      target: app
    container_name: queue
    env_file:
      - .env
    environment:
      APP_SEED: "false"
    command: start-queue
    depends_on:
      mysql:
        condition: service_healthy

  nginx:
    build:
      args:
          APP_NAME: ${APP_NAME}
          BROADCAST_CONNECTION: ${BROADCAST_CONNECTION}
          PUSHER_APP_KEY: ${PUSHER_APP_KEY}
          PUSHER_APP_CLUSTER: ${PUSHER_APP_CLUSTER}
          VITE_FIREBASE_API_KEY: ${VITE_FIREBASE_API_KEY}
          VITE_FIREBASE_AUTH_DOMAIN: ${VITE_FIREBASE_AUTH_DOMAIN}
          VITE_FIREBASE_PROJECT_ID: ${VITE_FIREBASE_PROJECT_ID}
          VITE_FIREBASE_STORAGE_BUCKET: ${VITE_FIREBASE_STORAGE_BUCKET}
      context: .
      dockerfile: Dockerfile
      target: nginx
    container_name: nginx
    ports:
      - "8000:80"
    depends_on:
      - app

  mysql:
    image: mysql:8.4
    container_name: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-ecommerce_db}
      MYSQL_ALLOW_EMPTY_PASSWORD: "0"
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-p${DB_PASSWORD:-root}" ]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  mysql_data:
