# start a server block
server {
    listen 80;
    server_name localhost; # handle requests for localhost, change this to domain if needed
    root /var/www/html/public; # set the document root to the public directory of the Laravel application, which is where the index.php file is located
    index index.php index.html; # look for index.php first, then index.html if index.php is not found

    charset utf-8; # set the character encoding to UTF-8 for proper handling of text
    client_max_body_size 20M; # set the maximum allowed size of the client request body

    # try_files is used to check if the requested URI exists as a file or directory, and if not, it will pass the request to index.php with the query string. This allows Laravel's routing system to handle the request.
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # handle requests for favicon.ico and robots.txt without logging access or not found errors, as these are common requests that do not need to be logged.
    location = /favicon.ico { 
        access_log off; 
        log_not_found off; 
    }
    location = /robots.txt  { 
        access_log off; 
        log_not_found off; 
    }

    # for requests to PHP files
    location ~ \.php$ {
        fastcgi_pass app:9000; # pass the request to the PHP-FPM service running in the app container on port 9000
        fastcgi_index index.php; # set the default file to index.php if the URI ends with a slash
        include fastcgi_params; # include the default FastCGI parameters provided by Nginx
        fastcgi_param SCRIPT_FILENAME /var/www/html/public$fastcgi_script_name; # set the SCRIPT_FILENAME parameter to the full path of the requested PHP file, which is necessary for PHP-FPM to execute the correct file
        fastcgi_param DOCUMENT_ROOT /var/www/html/public; # set the DOCUMENT_ROOT parameter to the public directory of the Laravel application, which is where the index.php file is located
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}
